{
 "title": "Monitor de sensores",
 "time": { "from": "2025-05-29T16:00:56.000Z", "to": "2025-05-29T16:45:01.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sensor CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  fecha AS \"time\",\r\n  valor\r\nFROM datos_sensor\r\nWHERE tipo = 'co2'\r\nORDER BY fecha\r\n"
    }
   ]
  },
  {
   "title": "Sensor COVS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fecha AS \"time\",\r\n  valor\r\nFROM datos_sensor\r\nWHERE tipo = 'covs'\r\nORDER BY fecha\r\n"
    }
   ]
  },
  {
   "title": "Humedad en tiempo real",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fecha AS \"time\",\r\n  valor\r\nFROM datos_sensor\r\nWHERE tipo = 'humedad'\r\nORDER BY fecha\r\n"
    }
   ]
  },
  {
   "title": "Temperatura en tiempo real",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  fecha AS time,\r\n  valor\r\nFROM datos_sensor\r\nWHERE tipo = 'temperatura'\r\nORDER BY fecha DESC\r\nLIMIT 100\r\n"
    }
   ]
  }
 ]
}